site_name: TIL
site_description: Today I Learn. 
site_url: https://songyunseop.github.io/TIL
site_author: Yunseop Song 
docs_dir: 'til'
site_dir: 'docs'

repo_name: TIL
repo_url: https://github.com/songyunseop/TIL

copyright: 'Copyright &copy; 2017 Yunseop Song'

theme:
    name: 'material'
    language: 'en'

extra:
    social:
        - type: 'github'
          link: 'https://github.com/songyunseop'
    disqus: 'songyunseop'

pages:
    - 'index.md'
    - Git:
        - 'git/git-command.md'
        - 'git/git-hook.md'
        - 'git/git-rm-already-committed-file.md'
    - Python:
        - 'python/arrow-key-is-not-working.md'
        - 'python/bitwise-operators.md'
        - 'python/contextlib.md'
        - 'python/lint-with-flake8.md'
        - 'python/nosetest-with-pdb.md'
        - 'python/nosetest-with-coverage.md'
        - 'python/packing-arguments.md'
        - 'python/python-comparing.md'
        - 'python/python-debugger.md'
        - 'python/setting-for-virtualenv.md'
    - HTTP:
        - 'http/OPTIONS-Method.md'
        - 'http/PATCH-Method.md'
        - 'http/URL-URN-URI.md'
    - MySQL:
        - 'mysql/add-fk-with-online-ddl.md'
        - 'mysql/show-processlist.md'
        - 'mysql/show-select-result-vertically.md'
        - 'mysql/some-case-insert-with-duplicated-key.md'
        - 'mysql/update-at-safe-mode.md'
    - Terminal:
        - 'terminal/kill-process.md'
        - 'terminal/move-to-start-or-end.md'
    - Tmux:
        - 'tmux/command.md'
        - 'tmux/settings-for-vim-color-scheme.md'
    - Vim:
        - 'vim/backspace-not-working.md'
        - 'vim/recording.md'
        - 'vim/replace.md'
        - 'vim/undo-redo.md'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      baselevel: 3
  - extra
  - meta

plugins:
    - search

